# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1Mswfd_SvrneQJZcf4kgkJND5Jigc2J

This task involves understanding the basic data
types in Python such as lists, dictionaries, and
sets.
"""

#list and its operations
list1=[1,23,4,6,3,43,3]
print(list1)
# add
list1.append(2)
print(list1)

#insert
list1.insert(1,2)
print(list1)

#remove
list1.remove(2)
print(list1)

#pop
list1.pop(1)
print(list1)

#clear
list1.clear()
print(list1)

#copy
list1.copy()
print(list1)

#count
list1.count(1)
print(list1)


#reverse
list1.reverse()
print(list1)

#sort
list1.sort()
print(list1)

#clear
list1.clear()
print(list1)

dict1={"name":"bajrang","age":23,"gender":"male"}
print(dict1)


#add
dict1["name"]="bajrangi"
print(dict1)

#remove
dict1.pop("age")
print(dict1)

#update
dict1.update({"name":"pawan"})
print(dict1)

#clear
dict1.clear()
print(dict1)

set1={1,2,3,4,3,2,1,5,6,7,8}
print(set1)

#add
set1.add(9)
print(set1)

#remove
set1.remove(1)
print(set1)

#pop
set1.pop()
print(set1)

#clear
set1.clear()
print(set1)











